package com.ang.model;

// Generated Oct 11, 2015 10:35:56 AM by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AngbooksGenre generated by hbm2java
 */
@Entity
@Table(name = "angbooks_genre", catalog = "angular_db")
public class AngbooksGenre implements java.io.Serializable {

	private Integer id;
	private Genre genre;
	private Angbooks angbooks;

	public AngbooksGenre() {
	}

	public AngbooksGenre(Genre genre, Angbooks angbooks) {
		this.genre = genre;
		this.angbooks = angbooks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.DETACH)
	@JoinColumn(name = "genre_id", nullable = false)
	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "angbooks_id", nullable = false)
	public Angbooks getAngbooks() {
		return this.angbooks;
	}

	public void setAngbooks(Angbooks angbooks) {
		this.angbooks = angbooks;
	}

}
