package com.ang.model;

// Generated Oct 11, 2015 10:35:56 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Angbooks generated by hbm2java
 */
@Entity
@Table(name = "angbooks", catalog = "angular_db")
public class Angbooks implements java.io.Serializable {

	private Integer bookId;
	private Price price;
	private String bookName;
	private String bookAuthor;
	private Date pubdate;
	private String country;
	private Integer pages;
	private String language;
	private String series;
	private String bookDesc;
	private Set<AngbooksGenre> angbooksGenres = new HashSet<AngbooksGenre>(0);

	public Angbooks() {
	}

	public Angbooks(Price price) {
		this.price = price;
	}

	public Angbooks(Price price, String bookName, String bookAuthor,
			Date pubdate, String country, Integer pages, String language,
			String series, String bookDesc, Set<AngbooksGenre> angbooksGenres) {
		this.price = price;
		this.bookName = bookName;
		this.bookAuthor = bookAuthor;
		this.pubdate = pubdate;
		this.country = country;
		this.pages = pages;
		this.language = language;
		this.series = series;
		this.bookDesc = bookDesc;
		this.angbooksGenres = angbooksGenres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "book_id", unique = true, nullable = false)
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "Price_id", nullable = false)
	public Price getPrice() {
		return this.price;
	}

	public void setPrice(Price price) {
		this.price = price;
	}

	@Column(name = "book_name", length = 2500)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "book_author", length = 2500)
	public String getBookAuthor() {
		return this.bookAuthor;
	}

	public void setBookAuthor(String bookAuthor) {
		this.bookAuthor = bookAuthor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pubdate", length = 19)
	public Date getPubdate() {
		return this.pubdate;
	}

	public void setPubdate(Date pubdate) {
		this.pubdate = pubdate;
	}

	@Column(name = "country", length = 2500)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "pages")
	public Integer getPages() {
		return this.pages;
	}

	public void setPages(Integer pages) {
		this.pages = pages;
	}

	@Column(name = "language", length = 250)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "series", length = 250)
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "book_desc", length = 65535)
	public String getBookDesc() {
		return this.bookDesc;
	}

	public void setBookDesc(String bookDesc) {
		this.bookDesc = bookDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "angbooks",cascade=CascadeType.ALL)
	public Set<AngbooksGenre> getAngbooksGenres() {
		return this.angbooksGenres;
	}

	public void setAngbooksGenres(Set<AngbooksGenre> angbooksGenres) {
		this.angbooksGenres = angbooksGenres;
	}

}
