package com.ang.model;

// Generated Oct 11, 2015 10:35:56 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name = "price", catalog = "angular_db")
public class Price implements java.io.Serializable {

	private Integer priceId;
	private int price;
	private Set<Angbooks> angbookses = new HashSet<Angbooks>(0);

	public Price() {
	}

	public Price(int price) {
		this.price = price;
	}

	public Price(int price, Set<Angbooks> angbookses) {
		this.price = price;
		this.angbookses = angbookses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "price_id", unique = true, nullable = false)
	public Integer getPriceId() {
		return this.priceId;
	}

	public void setPriceId(Integer priceId) {
		this.priceId = priceId;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "price")
	public Set<Angbooks> getAngbookses() {
		return this.angbookses;
	}

	public void setAngbookses(Set<Angbooks> angbookses) {
		this.angbookses = angbookses;
	}

}
